# Generated by Django 3.1.2 on 2020-10-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='rating_general',
        ),
    ]
