# Generated by Django 3.1.2 on 2020-10-19 20:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_remove_anime_rating_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/Animes/'),
        ),
        migrations.AddField(
            model_name='anime',
            name='opening',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='anime',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='anime',
            name='sinopsis',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
