# Generated by Django 3.1.2 on 2020-10-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_auto_20201019_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_anime', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Descripcion del Anime')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/Animes/')),
            ],
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
