# Generated by Django 3.1.2 on 2020-10-28 23:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_auto_20201028_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
