# Generated by Django 3.1.2 on 2020-10-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_auto_20201029_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/Galeria/'),
        ),
    ]
