# Generated by Django 3.1.2 on 2020-10-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0015_auto_20201030_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/'),
        ),
    ]
