# Generated by Django 3.1.2 on 2020-10-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0017_auto_20201030_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='sinopsis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
