# Generated by Django 3.1.2 on 2020-10-31 18:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0018_auto_20201031_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['nombre_anime']},
        ),
        migrations.AlterModelOptions(
            name='galeria',
            options={'ordering': ['nombre_anime']},
        ),
        migrations.AlterField(
            model_name='galeria',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
