# Generated by Django 3.1.2 on 2020-11-23 23:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0020_anime_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
