# Generated by Django 3.1.2 on 2020-11-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0022_anime_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='opening',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
