# Generated by Django 3.1.2 on 2020-11-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0023_auto_20201123_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='nombre_anime',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='anime',
            name='sinopsis',
            field=models.TextField(max_length=1000),
        ),
    ]
